snowflake_account   = "ur59996"
snowflake_password  = "Htek@#1214"
snowflake_region    = "ap-southeast-1.aws"
snowflake_user      = "ASHISH"
snowflake_warehouse = "COMPUTE_WH"
snowflake_role      = "ACCOUNTADMIN"
