name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0  # Use the latest version that is compatible with your configuration

    - name: Log in to Terraform Cloud
      run: terraform login ${{ secrets.TF_API_TOKEN }}

    - name: Set up environment variables
      run: |
        echo "TF_VAR_SNOWFLAKE_USER=$(grep SNOWFLAKE_USER main.tfvars | cut -d= -f2)" >> $GITHUB_ENV
        echo "TF_VAR_SNOWFLAKE_PASSWORD=$(grep SNOWFLAKE_PASSWORD main.tfvars | cut -d= -f2)" >> $GITHUB_ENV
        echo "TF_VAR_SNOWFLAKE_ACCOUNT=$(grep SNOWFLAKE_ACCOUNT main.tfvars | cut -d= -f2)" >> $GITHUB_ENV
        echo "TF_VAR_SNOWFLAKE_REGION=$(grep SNOWFLAKE_REGION main.tfvars | cut -d= -f2)" >> $GITHUB_ENV

    - name: Terraform Init
      run: terraform init
